packages:
  - 'apps/*'
  - 'libs/*'

# Catalog 配置 - 集中管理依赖版本
catalog:
  # NestJS 核心包
  '@nestjs/common': '^11.1.12'
  '@nestjs/core': '^11.1.12'
  '@nestjs/platform-express': '^11.1.12'
  '@nestjs/cli': '^11.0.0'
  '@nestjs/schematics': '^11.0.9'
  '@nestjs/testing': '^11.1.12'
  '@nestjs/cqrs': '^11.0.0'
  '@nestjs/swagger': '^11.2.5'
  '@nestjs/jwt': '^11.0.0'
  '@nestjs/passport': '^11.0.0'
  '@nestjs/graphql': '^12.1.0'
  '@nestjs/apollo': '^12.1.0'

  # MikroORM 相关包
  '@mikro-orm/core': '^6.6.5'
  '@mikro-orm/nestjs': '^6.1.1'
  '@mikro-orm/postgresql': '^6.6.5'
  '@mikro-orm/cli': '^6.5.8'

  # 验证和转换
  'class-validator': '^0.14.1'
  'class-transformer': '^0.5.1'

  # 认证相关
  'passport': '^0.7.0'
  'passport-jwt': '^4.0.1'
  'bcrypt': '^5.1.1'

  # GraphQL 相关
  'graphql': '^16.9.0'
  'apollo-server-express': '^3.12.1'

  # 工具库
  'rxjs': '^7.8.1'
  'nestjs-cls': '^5.1.0'
  'dotenv': '^17.2.3'
  'chalk': '^4.1.2'
  'reflect-metadata': '^0.2.2'

  # TypeScript 相关
  'typescript': '^5.7.3'
  '@types/node': '^22.10.7'
  '@types/express': '^5.0.0'
  '@types/passport-jwt': '^4.0.1'
  '@types/bcrypt': '^5.0.2'

  # 开发工具
  'jest': '^29.7.0'
  'ts-jest': '^29.2.5'
  'ts-node': '^10.9.2'
  'rimraf': '^6.0.1'
